pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock    
        '''
    }
  }
  stages {
    stage('Clone Repository') {
      steps {
        container('maven') {
             git branch: 'master', changelog: false, poll: false, url: 'https://github.com/prajwalakhuj/k8s-mastery.git'
        }
      }
    }  
    stage('Login Into Docker') {
      steps {
        container('docker') {
          sh 'docker login --username xxxxxx --password xxxxxxx'
      }
    }
    }
    stage('Build Docker Images') {
      steps {
        container('docker') {
          dir("sa-frontend") {
            sh 'docker build -t prajwalakhuj/sentiment-analysis-frontend:latest .'
          }
          dir("sa-webapp") {
            sh 'docker build -t prajwalakhuj/sentiment-analysis-web-app:latest .'
          }
          dir("sa-logic") {
            sh 'docker build -t prajwalakhuj/sentiment-analysis-logic:latest .'
          }
        }
      }
    }
     stage('Push Images Docker to DockerHub') {
      steps {
        container('docker') {
          sh 'docker push prajwalakhuj/sentiment-analysis-frontend:latest'
          sh 'docker push prajwalakhuj/sentiment-analysis-web-app:latest'
          sh 'docker push prajwalakhuj/sentiment-analysis-logic:latest'
      }
     }
     }
  }
    post {
      always {
        container('docker') {
          sh 'docker logout'
      }
      }
    }
}
