apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: sa-frontend
spec:
  selector:                                               
    matchLabels:
      app: sa-frontend                                    
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:                                               
    metadata:
      labels:
        app: sa-frontend                                  
    spec:
      containers:
        - image: prajwalakhuj/sentiment-analysis-frontend:k3s-V1.0
          imagePullPolicy: Always                      
          name: sa-frontend
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service            
metadata:
  name: sa-frontend-svc
spec:
  type: NodePort    
  ports:
  - port: 80               
    protocol: TCP          
    targetPort: 80
    nodePort: 30001         
  selector:                
    app: sa-frontend       
